"""empty message

Revision ID: ef2c890c1fc0
Revises: 8dd3f0ca6772
Create Date: 2024-02-23 14:25:58.991827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef2c890c1fc0'
down_revision = '8dd3f0ca6772'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.String(length=250), nullable=False),
    sa.Column('file_name', sa.String(length=250), nullable=False),
    sa.Column('MIME', sa.String(length=250), nullable=False),
    sa.Column('MD5', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_images'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    # ### end Alembic commands ###
